service: tesla-notifier

app: tesla-notifier
org: irwin

custom:
  bucket: tesla-notifier

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - sns:Publish
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        Fn::Join: ['', [Fn::GetAtt: [ Bucket, Arn ], '/*'] ]

functions:
  notifier:
    handler: src/handler.handler
    events:
      - schedule: rate(1 minute)
    environment:
      BUCKET: ${self:custom.bucket}
      REGION: ${opt:region}
      EMAIL_SOURCE: ${env:EMAIL_SOURCE}
      EMAIL_TO: ${env:EMAIL_TO}
      EMAIL_CC: ${env:EMAIL_CC}
      SMS_TO: ${env:SMS_TO}

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}