on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        args: install
    - uses: serverless/github-action@master
      with:
        args: deploy
      env:
        EMAIL_CC: ${{ secrets.EMAIL_CC }}
        EMAIL_SOURCE: ${{ secrets.EMAIL_CC }}
        EMAIL_TO: ${{ secrets.EMAIL_CC }}
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        SERVERLESS_APP: ${{ secrets.SERVERLESS_APP }}
        SERVERLESS_ORG: ${{ secrets.SERVERLESS_ORG }}
        SMS_TO: ${{ secrets.SMS_TO }}
